# -*- coding : utf-8 -*-
# Author    => Albertus Restiyanto Pramayudha
# email     => xabre0010@gmail.com
# linkedin  => https://www.linkedin.com/in/albertus-restiyanto-pramayudha-470261a8/
# youtube   => https://www.youtube.com/channel/UCCtgLDIfqehJ1R8cohMeTXA

from . import yudha_res_partner
from . import yudha_master_department
from . import yudha_master_golongan
from . import yudha_register_tabungan
from . import yudha_master_jenis_tabungan
from . import yudha_master_jenis_deposito
from . import yudha_rates_deposito
from . import yudha_rates_tabungan
from . import yudha_asal_perusahaan
from . import yudha_iuran_pokok
from . import yudha_iuran_wajib
from . import yudha_iuran_wajib_setor
from . import yudha_iuran_sukarela
from . import yudha_tabungan_rutin
from . import yudha_deposito
from . import yudha_peminjaman_dana
from . import yudha_peminjaman_konsumtif
from . import yudha_peminjaman_syariah
from . import yudha_peminjaman_barang
from . import yudha_peminjaman_sembako
from . import yudha_validasi_harian
from . import yudha_validasi_sembako
from . import yudha_validasi_bulanan
from . import yudha_laporan_harian
from . import yudha_laporan_detail_anggota
from . import yudha_laporan_bulanan
from . import yudha_settings
from . import yudha_pos_order
from . import yudha_pelunasan_dana
from . import yudha_pelunasan_barang
from . import yudha_pelunasan_konsumtif
from . import yudha_pelunasan_sembako
from . import yudha_pelunasan_syariah
from . import yudha_account_payment
from . import yudha_perhitungan_bunga
from . import yudha_pencairan_deposito
from . import yudha_schedule_otomatis
from . import yudha_product